### PR TITLE
do not set orcid as netid

### PR DESCRIPTION
**Pull request by olli-gold**
The OAuth authentication service in DSpace CRIS sets the ORCID as the netid in the eperson table. This might conflict with LDAP login as the netid is associated with LDAP. If you are using both LDAP and OAuth and have set a group, which should get assigned to anyone logging in with LDAP, this group will also be assigned when someone logs in with OAuth/Orcid. This might not be expected behaviour.

So my proposal in this PR is not to set the netid for OAuth login as this is not necessary at all.

### CODE REVIEW

**Comment by olli-gold** [comment]
I have taken a deeper look into this and found another problem with the OAuth login. If a user on ORCID has several email addresses, its obviously absolutely random, which one is returned as the first one. So it might happen, that the user is mapped to different accounts on DSpace CRIS.

In my opinion this is not good and I would rather test all of the emailaddresses OAuth login gets from Orcid to check against DSpace CRIS. The first match can be taken to assign the DSpace ePerson to the Orcid user. A new user should only be generated if there is no match.

I'll try to propose a solution for that with this PR in the next days.

**Comment by lap82** [comment]
Thank you Oliver! But we can't accept this PR due to the fact that the connector from ORCID to DSpace-CRIS is not limited only the login feature, but behind the scene there are others features. If take a look at https://github.com/4Science/DSpace/blob/dspace-5_x_x-cris/dspace/config/spring/cris/cris-postlogin.xml there are a post login action to bind orcid profile (using netid) from the EPerson to the ResearcherPage. So, I think that a development to do is move the orcid from netid to a metadatafield, and using that in the other part of the software. After that I can accept your PR. BTW I'm honored If you can help us on that.

**Comment by olli-gold** [comment]
Thank you for your comment, Luigi! It's very helpful to know about that. I'll try to improve the PR as you suggested and will be honoured, if you can accept it then.

**Comment by olli-gold** [comment]
I thought a lot about this issue and now I am convinced, that my approach is probably not the best one as it conflicts with other functions. Perhaps there is a better way to solve the original issue without stopping to insert the orcid into the netid field - I'm thinking about a login method field in the eperson table, that should be used for group associations.
So I guess I'll have to revert this PR unfortunately. :-(

**Comment by lap82** [comment]
Ok thank you very much Oliver! I close the PR.

**Comment by lap82** [comment]
Hello Oliver,
in the new DSpace-CRIS 5.8.0 I have applied your suggestion, to not use the netid for store orcid information. Please check if now it is usefull for your use case.
Thank you very much.

**Comment by olli-gold** [comment]
Thank you for applying my suggestion! I'll check that locally and I hope, there are no unwanted effects anywhere else in the system.

**Comment by olli-gold** [comment]
In my system the post login action to bind the orcid profile from the EPerson to the ResearcherPage you mentioned in comment https://github.com/4Science/DSpace/pull/7#issuecomment-318607630 is not working. But maybe I misunderstood something. Here is my scenario:
We are authenticating our users over Shibboleth. This way we also get their ORCID iD, if its in the persons Shibboleth profile. We are writing this ORCID to the EPerson profile. If there is a ResearcherPage with this ORCID, this should be bound to the EPerson profile, if I understood you correctly. But this is not working properly here. Although I have an EPerson with the ORCID in the orcid metadata field, the ResearcherPage with the same ORCID is not bound to it automatically. 

I have to admit, that, as we do not have a production system yet, this is only a constructed scenario, because we do not have any real researcher pages yet (and as far as I know we will not be able to set the ORCID into the researcher profile, since the author has to do that himself). So maybe this scenario is just a theoretical one, but I think it should work nonetheless.

**Pull request closed without merging**
