### PR TITLE
Port "identifiers during submission" to DSpace CRIS 7 REST

### PR DESCRIPTION
**Pull request by kshepherd**
## References
This is a port of the simple submission step (now section) for DSpace 6.3

* 6.3 module: https://github.com/the-library-code/identifiers-enduring-submission/tree/dspace-6.3-addition
* dspace-angular UI component PR: https://github.com/4Science/dspace-angular/pull/5
* Related to [REST Contract - submission section types ](https://github.com/4Science/Rest7Contract/blob/dspace-cris-7/submissionsection-types.md) - a new type will need to be added

## Description
A new submission section class populates submission section data with identifiers that will be / have been minted for an item (in the case of DOIs, they are pre-minted before returning the section data) so that submitters can update their PDFs or other references with DOIs, Handles etc before completing the submission.

This component was contributed by The Library Code with the support of Technische Universität Hamburg.

## Instructions for Reviewers
**NOTE**: The Integration Test for this work is still a work-in-progress. The step works in real usage, but for some reason the REST / API test environment is not adding the new section to test items submissions. Any guidance is appreciated.

**BUG**: There is a strange race condition when an item filter is used with the DOI provider, where the subscription to sectionData means that when the item goes from "no match" to "match" on the DOI filter, it reserves OK, but the next time the item is updated the DOI will be minted again, and receive a new URI. This is still being analyzed - there are probably improvements that can be made to limit / throttle the calls back to the section data?

List of changes in this PR:
* New step and integration test: `ShowIdentifiersStep` and `SubmissionShowIdentifiersRestIT`
* New simple bean (data model): `DataIdentifiers`
* Test submission configuration updated for steps and submission processes, to include the new `identifiers` section

To test:
* Add a new item (right now, the step is just configured for publication form)
* Check that the handle is displayed in the first section accordion
* If DOIs are enabled, check that the DOI is displayed in the first section accordion

## Checklist
_This checklist provides a reminder of what we are going to look for when reviewing your PR. You need not complete this checklist prior to creating your PR (draft PRs are always welcome). If you are unsure about an item in the checklist, don't hesitate to ask. We're here to help!_

- [x] My PR is small in size (e.g. less than 1,000 lines of code, not including comments & integration tests). Exceptions may be made if previously agreed upon.
- [x] My PR passes Checkstyle validation based on the [Code Style Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Style+Guide).
- [x] My PR includes Javadoc for _all new (or modified) public methods and classes_. It also includes Javadoc for large or complex private methods.
- [ ] My PR passes all tests and includes new/updated Unit or Integration Tests based on the [Code Testing Guide](https://wiki.lyrasis.org/display/DSPACE/Code+Testing+Guide).
- [x] If my PR includes new, third-party dependencies (in any `pom.xml`), I've made sure their licenses align with the [DSpace BSD License](https://github.com/DSpace/DSpace/blob/main/LICENSE) based on the [Licensing of Contributions](https://wiki.lyrasis.org/display/DSPACE/Code+Contribution+Guidelines#CodeContributionGuidelines-LicensingofContributions) documentation.
- [x] If my PR modifies the REST API, I've linked to the REST Contract page (or open PR) related to this change.

### CODE REVIEW

**Comment by pnbecker** [comment]
We‘ll continue to work on this in January. Some help regarding the integration tests would be great.

**Comment by abollini** [comment]
hi @pnbecker , @kshepherd 
are you still working on that?
other than the IT noted in the original description we would like to get a PR also for the REST Contract.

Speaking about the functionality: we have implemented something similar as customization for a couple of projects. In our case the request was a bit more complicated because it involve a workflow where the submitter asks to reserve a DOI and someone else need to approve. 
The general idea and the implementation that you have provided seems to be a good standard solution to provide out-of-box so we are willing to have it finalized and available in DSpace-CRIS by default (thanks for proposing that!).
Few remarks:
- we would prefer to have the minting process triggered manually by the user. The user should click a button to reserve an identifier and not get them reserved automatically all the times (otherwise any test submission will reserve one)
- what we should do if the user reserve a DOI and later on change the item in a way that the DOI should be not longer reserved? we see different options: **ignore the filter**, the DOI has been reserved so it will be enabled on the item is archived (risky as this could allow user to bypass the filter and could also result in error/low quality metadata sent to datacite);  **ignore the reservation** a message to inform the user that the item doesn't deserve any more the identifier should be provided requiring acknowledgement before proceed; **prevent the item to be submitted (validation issue)** until the condition to get a DOI are restored
- the scenario where the DOI is reserved but the item is deleted should be tested to verify that orphan reservation create no issue in the minting process

**Comment by kshepherd** [comment]
Hi @abollini , I have since opened a PR against core DSpace 7 with a more simple (and robust) implementation, and working integration and unit tests: https://github.com/DSpace/DSpace/pull/8423 and https://github.com/DSpace/dspace-angular/pull/1740

The new DSpace PR does the same functionality. Regarding your questions:

1. I can see this being a useful additional configurable option... I can find out whether it's in scope for me to add to the existing PR or if it's something that might have to wait for a future improvement. Perhaps one thing we should ensure here is that when the DOI organiser runs, it only registers DOIs online for archived items? The local reservation for test submissions isn't too much of a problem that I can see, we have a lot of numbers to use, but I understand your point.
2. In the DSpace implementation, you'll see that this is handled by the DOI consumer deleting a DOI if the filter now evaluates as false or reserving again if the filter evaluates to true (as long as the item is still in workspace or workflow). I can understand that you might have the same ID namespace concerns as the previous answer, but it worked well in my testing to at least prevent the ineligible items from getting DOIs
3. I will test for this scenario

**Comment by kshepherd** [comment]
Just confirming that we're taking this useful feedback and will look at ways to ensure the filter and the pre-registered identifiers can work well together. At the moment it looks like the approach will be to locally 'reserve' a DOI with a new PENDING status that won't actually be registered if the filter doesn't return true, but will at least remain persisted in the doi table in the event that the item later becomes eligible, or an administrator manually approves a DOI. I'll see how much I can make configurable too.

**Pull request closed without merging**
